version: '3.8'

services:
  api:
    build: ./api
    networks:
      - app-network

  frontend:
    build: ./frontend
    networks:
      - app-network

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge